apiVersion: v1
kind: Pod
metadata:
  name: debian
  namespace: default
  labels:
    app: debian
spec:
  containers:
  - name: debian
    image: debian:stable-slim
    command: ["sleep", "infinity"]
    tty: true
    stdin: true
  restartPolicy: Never

