apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  sources:
    - path: 'clusterissuer'
      repoURL: 'https://github.com/cod3mas0n/hetz-cluster.git'
      targetRevision: main

    - path: 'cert-manager-v1.19.1'
      repoURL: 'https://github.com/cod3mas0n/hetz-cluster.git'
      targetRevision: main
      helm:
        releaseName: cert-manager
        valueFiles:
          - values.yaml

  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
