apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crypto-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: crypto-currency-exchange
  sources:
    - path: 'kubernetes'
      repoURL: 'https://github.com/cod3mas0n/crypto-currency-exchange.git'
      targetRevision: master

  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
