apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  sources:
    - path: 'loki-6.45.2'
      repoURL: 'https://github.com/cod3mas0n/hetz-cluster.git'
      targetRevision: main
      helm:
        releaseName: loki
        valueFiles:
          - single-binary-values.yaml

  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
