apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-backup
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: database
  sources:
    - path: 'postgresql-backup'
      repoURL: 'https://github.com/cod3mas0n/hetz-cluster.git'
      targetRevision: main

  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
