apiVersion: batch/v1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: database
spec:
  schedule: "0 */12 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          # imagePullSecrets:
          #   - name: regcred
          containers:
          - name: postgres-backup
            image: docker.io/alimehr75/postgres-backup:latest
            imagePullPolicy: Always
            envFrom:
              - configMapRef:
                  name: postgres-backup-cm
                  optional: false
              - secretRef:
                  name: postgres-backup-secret
                  optional: false
            resources:
              requests:
                cpu: "1"
                memory: "1Gi"
              limits:
                cpu: "2"
                memory: "2Gi"
          restartPolicy: Never
